import { Inter } from "next/font/google";
import "./global.css"
import { UiProvider } from "../Providers/UiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UiProvider>
         <div>
            {children}
         </div>
        </UiProvider>
      </body>
    </html>
  );
}
